#!/usr/bin/env python3
"""Colour tmux panes and the terminal by person, repo, branch, and session.

Every pane gets a title strip of up to four coloured blocks, drawn by tmux from
the pane's own current path and title, so it stays right for Claude, Codex and
plain shells alike and needs no agent session:

    [ person ][ repo ][ branch ][ session ]

Block colours come from one baked table of 40 colours, chosen by Oklab
farthest-point search (``docs/branch-bg-colour-eval.py --text-flip``) so that
black or white label text reads on every one. Person, repo and branch names are
assigned colours through a per-machine registry (lowest free slot first, least
recently seen slot reused when full); session names are hashed because they
churn. The pane field behind the text is a near-black shade of the repo colour,
and the same shade goes to the terminal window by OSC 11 when an agent session
starts there.

Modes:
    branch-bg.py                 SessionStart hook: OSC 11, pane field, ensure
                                 the tmux strip is installed for this server.
    branch-bg.py --strip PATH TITLE
                                 Print the strip format and the field colour
                                 for a pane (called by hooks/branch-strip.sh).

Brian, 2026-10-09: the colour is a highlight, not the field under white text;
one block per person, repo, branch and session; black or white text as needed.
"""

from __future__ import annotations  # keep PEP 604 annotations runtime-free on <3.10

import fcntl
import hashlib
import json
import os
import subprocess
import sys
import time
from pathlib import Path

# (block colour, label text colour); farthest-point order, so the first N are
# the best-separated N. Generated by:
#   docs/branch-bg-colour-eval.py --text-flip --ratio 4.5 --repo-gap 5
#       --max-chroma 0.16 --min-lightness 0.30 --emit-blocks blocks.json
BLOCKS = [
    ("#6987f0", "#000000"),
    ("#ffff78", "#000000"),
    ("#5f0000", "#ffffff"),
    ("#e17d0f", "#000000"),
    ("#006900", "#ffffff"),
    ("#ffbeff", "#000000"),
    ("#003c96", "#ffffff"),
    ("#00cd9b", "#000000"),
    ("#91327d", "#ffffff"),
    ("#d769af", "#000000"),
    ("#91faff", "#000000"),
    ("#738273", "#000000"),
    ("#00372d", "#ffffff"),
    ("#e1c38c", "#000000"),
    ("#874600", "#ffffff"),
    ("#4b005f", "#ffffff"),
    ("#69c3fa", "#000000"),
    ("#91a000", "#000000"),
    ("#2d5f69", "#ffffff"),
    ("#c84b4b", "#ffffff"),
    ("#afa0aa", "#000000"),
    ("#c396ff", "#000000"),
    ("#9beb82", "#000000"),
    ("#ff8c91", "#000000"),
    ("#00a5be", "#000000"),
    ("#ffebd7", "#000000"),
    ("#199141", "#000000"),
    ("#8c69a5", "#000000"),
    ("#5a3750", "#ffffff"),
    ("#5f46aa", "#ffffff"),
    ("#a56e00", "#000000"),
    ("#007db9", "#000000"),
    ("#8c0a2d", "#ffffff"),
    ("#4b4600", "#ffffff"),
    ("#96d2c3", "#000000"),
    ("#cdb400", "#000000"),
    ("#232d5a", "#ffffff"),
    ("#b47882", "#000000"),
    ("#ff91dc", "#000000"),
    ("#9bb47d", "#000000"),
]
# Fixed colours that bypass the registry and never appear in BLOCKS.
# Brian, 2026-10-09: "main should always be BRIGHT RED because usually it's
# not a good idea to work there."
PINNED = {"branch": {"main": ("#ff0000", "#000000"), "master": ("#ff0000", "#000000")}}
KINDS = ("person", "repo", "branch")  # registry-assigned; "session" is hashed
# Each kind starts its slot search at a different point of the table, so the
# first person, first repo and first branch do not all land on block 0.
KIND_OFFSET = {"person": 0, "repo": 13, "branch": 26, "session": 33, "place": 7}
FIELD_SHADE = 0.80  # the pane field is this far from the repo colour toward black
REGISTRY_VERSION = 2
STRIP_SCRIPT = Path(__file__).resolve().with_name("branch-strip.sh")


def now() -> float:
    return time.time()


# --- what a pane is ---------------------------------------------------------


def git_identity(path: str) -> tuple[str | None, str | None]:
    """(real git common dir, branch) for ``path``, or (None, None)."""
    try:
        common = subprocess.run(
            ["git", "-C", path, "rev-parse", "--git-common-dir"],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
        branch = subprocess.run(
            ["git", "-C", path, "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
        if common.returncode == 0 and branch.returncode == 0:
            common_dir = Path(common.stdout.strip())
            if not common_dir.is_absolute():
                common_dir = Path(path) / common_dir
            return os.path.realpath(common_dir), branch.stdout.strip()
    except subprocess.TimeoutExpired:
        pass
    except FileNotFoundError:
        pass
    return None, None


def person_of(path: str) -> str:
    """The directory under a ``people`` segment of ``path``, else ''."""
    parts = Path(path).parts
    for index, part in enumerate(parts[:-1]):
        if part == "people":
            return parts[index + 1]
    return ""


def repo_name(common_dir: str) -> str:
    """Display name of a repo from its common dir (``…/name/.git`` → ``name``)."""
    path = Path(common_dir)
    return path.parent.name if path.name == ".git" else path.name


def session_of(title: str) -> str:
    """The session label inside a pane title, or '' for a plain shell.

    Claude Code titles its pane ``✳ <session name>``. Codex titles its pane
    ``<state> | <repo> | <branch> | <task or id> | <model effort>``.
    """
    title = title.strip()
    if title.startswith("✳"):
        return title[1:].strip()
    parts = [p.strip() for p in title.split(" | ")]
    if len(parts) >= 4:
        return parts[3]
    return ""


def place_of(path: str) -> str:
    """A coarse location for a pane outside any repo or person: the first
    directory under home, else the first two components of the path."""
    try:
        relative = Path(path).resolve().relative_to(Path("~").expanduser())
    except ValueError:
        parts = Path(path).parts
        return "/".join(parts[:3]) if len(parts) > 1 else path
    except OSError:
        return path
    return relative.parts[0] if relative.parts else "~"


def describe(path: str, title: str) -> dict:
    """Names for each block of the pane at ``path`` with tmux title ``title``."""
    common_dir, branch = git_identity(path)
    return {
        "person": person_of(path),
        "repo_key": common_dir or "",
        "repo": repo_name(common_dir) if common_dir else "",
        "branch": branch or "",
        "session": session_of(title),
        "place": place_of(path),
    }


# --- which colour a name gets ----------------------------------------------


def _hash_index(key: str, modulus: int) -> int:
    return int(hashlib.sha256(key.encode()).hexdigest()[:8], 16) % modulus


def registry_path() -> Path:
    override = os.environ.get("BRANCH_BG_REGISTRY")
    if override:
        return Path(override)
    state_home = os.environ.get("XDG_STATE_HOME")
    home_state = Path("~").expanduser() / ".local" / "state"
    base = Path(state_home) if state_home else home_state
    return base / "branch-bg" / "registry.json"


def _empty_registry() -> dict:
    return {"version": REGISTRY_VERSION, "kinds": {kind: {} for kind in KINDS}}


def _load_registry(path: Path) -> dict:
    try:
        data = json.loads(path.read_text())
    except FileNotFoundError:
        return _empty_registry()
    except ValueError:
        return _empty_registry()
    if (
        not isinstance(data, dict)
        or data.get("version") != REGISTRY_VERSION
        or not isinstance(data.get("kinds"), dict)
    ):
        return _empty_registry()
    for kind in KINDS:
        data["kinds"].setdefault(kind, {})
    return data


def _write_registry(path: Path, data: dict) -> None:
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(json.dumps(data, indent=1, sort_keys=True))
    tmp.replace(path)


def _assign_slot(table: dict, name: str, offset: int) -> int:
    """Mutate ``table`` (name → {slot, seen}) to hold ``name``; return its slot."""
    entry = table.get(name)
    if entry is None or not isinstance(entry.get("slot"), int):
        taken = {e.get("slot") for e in table.values() if isinstance(e, dict)}
        slot = None
        for step in range(len(BLOCKS)):
            candidate = (offset + step) % len(BLOCKS)
            if candidate not in taken:
                slot = candidate
                break
        if slot is None:
            stalest = min(table, key=lambda key: table[key].get("seen", 0.0))
            slot = table[stalest]["slot"]
            del table[stalest]
        entry = {"slot": slot}
        table[name] = entry
    entry["seen"] = now()
    return entry["slot"]


def _hashed_slot(kind: str, name: str) -> int:
    return (KIND_OFFSET[kind] + _hash_index(name, len(BLOCKS))) % len(BLOCKS)


def assign(names: dict) -> dict:
    """Block index per kind for the non-empty names; registry, else hash."""
    wanted = {kind: names.get(kind, "") for kind in KINDS}
    if names.get("repo_key"):
        wanted["repo"] = names["repo_key"]
    for kind, pinned in PINNED.items():
        if wanted.get(kind) in pinned:
            wanted[kind] = ""  # pinned names take no registry slot
    slots = {}
    path = registry_path()
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        lock = path.with_name(path.name + ".lock")
        with lock.open("a") as handle:
            fcntl.flock(handle, fcntl.LOCK_EX)
            data = _load_registry(path)
            for kind, name in wanted.items():
                if name:
                    table = data["kinds"][kind]
                    slots[kind] = _assign_slot(table, name, KIND_OFFSET[kind])
            _write_registry(path, data)
    except OSError:
        for kind, name in wanted.items():
            if name:
                slots[kind] = _hashed_slot(kind, name)
    session = names.get("session", "")
    if session:
        # Hashed, so step past any block this strip already uses.
        slot = _hashed_slot("session", session)
        while slot in slots.values():
            slot = (slot + 1) % len(BLOCKS)
        slots["session"] = slot
    place = names.get("place", "")
    if place:
        slots["place"] = _hashed_slot("place", place)
    return slots


# --- drawing ----------------------------------------------------------------


def _channels(colour: str) -> list[int]:
    return [int(colour[i : i + 2], 16) for i in (1, 3, 5)]


def shade(colour: str, amount: float = FIELD_SHADE) -> str:
    """A darker shade of ``colour`` for the field behind text."""
    lowered = [round(c * (1 - amount)) for c in _channels(colour)]
    return "#" + "".join(f"{c:02x}" for c in lowered)


def field_for(slots: dict) -> str:
    """The pane field: a near-black shade of the most specific thing known.

    Repo, else person, else the pane's place in the filesystem, so a pane is
    never painted plain black; Brian, 2026-10-09: "we should be able to derive
    things".
    """
    for kind in ("repo", "person", "place"):
        if kind in slots:
            return shade(BLOCKS[slots[kind]][0])
    return "#000000"


def block_colour(kind: str, label: str, slots: dict) -> tuple[str, str] | None:
    """(colour, text colour) for one block: a pinned colour, else its slot."""
    pinned = PINNED.get(kind, {}).get(label)
    if pinned:
        return pinned
    if kind in slots:
        return BLOCKS[slots[kind]]
    return None


def strip_format(names: dict, slots: dict) -> str:
    """The tmux ``pane-border-format`` text: one styled block per known name."""
    pieces = []
    for kind in ("person", "repo", "branch", "session"):
        label = names.get(kind, "")
        colours = block_colour(kind, label, slots) if label else None
        if colours is None:
            continue
        colour, text = colours
        label = label.replace("#", "##")
        pieces.append(f"#[bg={colour},fg={text},bold] {label} ")
    if not pieces:
        return ""
    return "".join(pieces) + "#[default]"


def find_terminal() -> str | None:
    """Walk up process tree to find the controlling terminal device."""
    pid = os.getpid()
    while pid > 1:
        try:
            fd0 = str(Path(f"/proc/{pid}/fd/0").readlink())
            if fd0.startswith("/dev/pts/") or fd0.startswith("/dev/tty"):
                return fd0
        except OSError:  # PermissionError is an OSError subclass
            pass
        try:
            with Path(f"/proc/{pid}/stat").open() as f:
                parts = f.read().split()
                pid = int(parts[3])  # ppid
        except OSError:
            break
        except ValueError:
            break
    return None


def set_terminal_bg(colour: str) -> None:
    """Set terminal background via OSC 11, walking process tree to find TTY."""
    tty_path = find_terminal()
    if not tty_path:
        return
    try:
        with Path(tty_path).open("w") as tty:
            tty.write(f"\033]11;{colour}\007")
    except OSError:
        pass


def run_tmux(argv: list[str]) -> str:
    try:
        done = subprocess.run(
            ["tmux", *argv],
            capture_output=True,
            text=True,
            timeout=2,
            check=False,
        )
    except subprocess.TimeoutExpired:
        return ""
    except FileNotFoundError:
        return ""
    return done.stdout if done.returncode == 0 else ""


def is_default_border_format(value: str) -> bool:
    """tmux's own default pane-border-format shows the index and quoted title."""
    return "#{pane_index}" in value and '"#{pane_title}"' in value


def ensure_tmux_strip() -> None:
    """Point the server's pane title strip at branch-strip.sh, once.

    Replaces tmux's default format or an earlier one of ours; a format set by
    hand is left alone.
    """
    current = run_tmux(["show-options", "-gv", "pane-border-format"])
    if STRIP_SCRIPT.name in current:
        return
    if current.strip() and not is_default_border_format(current):
        return
    # `q:` already shell-escapes the value, so the arguments go unquoted.
    command = (
        f'#(bash "{STRIP_SCRIPT}" '
        "#{q:pane_current_path} #{q:pane_title} #{pane_id})"
    )
    run_tmux(["set-option", "-g", "pane-border-status", "top"])
    run_tmux(["set-option", "-g", "pane-border-format", command])


def apply_session_start(path: str) -> None:
    """The SessionStart hook: field to the terminal and this pane; strip on."""
    names = describe(path, "")
    slots = assign(names)
    field = field_for(slots)
    set_terminal_bg(field)
    pane = os.environ.get("TMUX_PANE")
    if pane:
        # A pane option, not select-pane: select-pane would also focus the pane.
        run_tmux(["set-option", "-p", "-t", pane, "window-style", f"bg={field}"])
        ensure_tmux_strip()


def strip_output(path: str, title: str) -> str:
    """Two lines for branch-strip.sh: the strip format, then the field colour."""
    names = describe(path, title)
    slots = assign(names)
    return strip_format(names, slots) + "\n" + field_for(slots) + "\n"


def main(argv: list[str] | None = None) -> None:
    args = sys.argv[1:] if argv is None else argv
    if len(args) == 3 and args[0] == "--strip":
        sys.stdout.write(strip_output(args[1], args[2]))
        return
    apply_session_start(str(Path.cwd()))


if __name__ == "__main__":
    main()
